name: CI

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: main
  workflow_dispatch:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - localbytes-plug-pm.yaml
          - minimal.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v6
        with:
          yaml_file: ${{ matrix.file }}
