name: Lint
concurrency: build-${{ github.ref }}

on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

jobs:
  ci:
    name: Build ${{ matrix.file }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        file:
          - localbytes-plug-pm.yaml
          - minimal.yaml
          - bulb/localbytes-bulb.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Write secrets file
        env:
          API_ENCRYPTION_KEY: ${{ secrets.ESPHOME_API_ENCRYPTION_KEY }}
          OTA_PASSWORD: ${{ secrets.ESPHOME_OTA_PASSWORD }}
        run: |
          cat > secrets.yaml <<SECRETS
          wifi_ssid: "placeholder"
          wifi_password: "placeholder123"
          api_encryption_key: "${API_ENCRYPTION_KEY}"
          ota_password: "${OTA_PASSWORD}"
          SECRETS
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@5f7befc3994ab0553e1de5d6fa4c3d9fece175dc # v6.0.1
        with:
          yaml-file: ${{ matrix.file }}
