name: Build and Publish ESPHome firmware and website

on: # yamllint disable-line rule:truthy
  push:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/publish-esphome.yml
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: localbytes-plug-pm.yaml
      # CHANGEME: Set the name of your project here:
      name: Local Bytes Power Monitor Smart Plug
